<?php
class ValidationResult
{
	const REGEX_MISSING = 'REGEX_MISSING';
	const REQUIRED_FIELD_EMPTY = 'REQUIRED_FIELD_EMPTY';
	const MAX_LENGTH_EXCEEDED = 'MAX_LENGTH_EXCEEDED';
	const INVALID_FORMAT = 'INVALID_FORMAT';
	const VALID = 'VALID';
}
?>
